services:
  postgres:
    image: postgres:latest
    networks:
      - my-network
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=forsit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d forsit"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
